//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSourceV2
{
    using System;
    
    public partial class prUserWiseMasterInfo_Result1
    {
        public string propertyid { get; set; }
        public string PropertyName { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string zip { get; set; }
        public string propertymanager { get; set; }
        public Nullable<int> WorkOrder { get; set; }
        public Nullable<int> WorkRequst { get; set; }
        public Nullable<int> PropertyInspection { get; set; }
        public Nullable<int> SnowReport { get; set; }
    }
}
