//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSourceV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<byte> allowsubmitform1 { get; set; }
        public Nullable<byte> allowsubmitform2 { get; set; }
        public Nullable<byte> allowdailyreportuploads { get; set; }
        public Nullable<byte> allowreportstatuschange { get; set; }
        public Nullable<byte> alloweditlogins { get; set; }
        public Nullable<byte> alloweditprops { get; set; }
        public Nullable<byte> allowsoftwaredownload { get; set; }
        public Nullable<byte> viewreports1 { get; set; }
        public Nullable<byte> viewreports2 { get; set; }
        public Nullable<byte> viewreports3 { get; set; }
        public string fullname { get; set; }
        public string emailaddress { get; set; }
        public string phonenumber { get; set; }
        public Nullable<byte> allowenterworkorder { get; set; }
        public Nullable<byte> alloweditworkorder { get; set; }
        public Nullable<byte> allowshowcost { get; set; }
        public Nullable<byte> allowviewvendors { get; set; }
        public Nullable<byte> allowviewpropdatasheets { get; set; }
        public string clientcode { get; set; }
        public Nullable<byte> alloweditbrixmorwo { get; set; }
        public Nullable<byte> allowedapprovebrixinvoices { get; set; }
        public Nullable<byte> allowedapprovebrixinvoices_ondemand { get; set; }
        public Nullable<byte> allowedapprovebrixinvoices_viewonly { get; set; }
        public string forcestartpage { get; set; }
        public Nullable<int> onlyallowiosaudits { get; set; }
        public Nullable<byte> uniadmin { get; set; }
        public Nullable<byte> univendor { get; set; }
    }
}
